config_name: "squad-en-7.5K-s42"

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${config_name}

task: "squad"
lang: "en"

seed: 42
device: "auto" # "auto" will use the best available device (CUDA > MPS > CPU)

model_id: "FacebookAI/xlm-roberta-base"
model_name: "XLM-R-Base"

lora:
  rank: 8
  alpha: 8
  dropout: 0.1
  target_modules: [
    # Not "all-linear" - exclude "qa_outputs" for QA
    "query",
    "key",
    "value",
    # Not all "dense" - exclude "lm_head.dense" for MLM
    "intermediate.dense",
    "output.dense",
  ]

data:
  train_size: 7500
  val_size: 1875

train:
  mini_batch_size: 4
  grad_accum_steps: 4
  num_epochs: 10
  max_steps: null
  lr: 1e-4
  lr_scheduler_type: "cosine"
  optim: "adamw_8bit"
  max_grad_norm: 1.0
  weight_decay: 0.01
  warmup_steps: 100
  eval_strategy: "steps"
  eval_steps: 300
  save_steps: 300
  load_best_model_at_end: true
  logging_steps: 100
  report_to: ["tensorboard", "wandb"]
  push_to_hub: true
  early_stopping_patience: 5

resume:
  model_id: null
  ckpt_step: null
