config_name: "wikipedia-vi-3K-s42_RTX3090"

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${config_name}

defaults:
  - wikipedia-vi-3K-s42
  - _self_

train:
  mini_batch_size: 8
  lr: 2e-4
  optim: "adamw_torch_fused"
