task: "wikipedia"
lang: "en"

seed: 42
device: "auto" # "auto" will use the best available device (CUDA > MPS > CPU)

model_id: "FacebookAI/xlm-roberta-base"
model_name: "XLM-R-Base"

lora:
  rank: 16
  alpha: 16
  dropout: 0.1
  target_modules: [
    # Not "all-linear", since we exclude "qa_outputs" for question answering tasks
    "query", 
    "key", 
    "value", 
    # Not all "dense" layers, since we exclude "lm_head.dense" for masked language modeling
    "intermediate.dense",
    "output.dense",
  ]

data:
  train_size: 10000
  val_size: 2500
  mlm_prob: 0.15

train:
  mini_batch_size: 4
  grad_accum_steps: 4
  num_epochs: 3
  lr: 2e-4
  lr_scheduler_type: "cosine"
  optim: "adamw_8bit"
  max_grad_norm: 1.0
  weight_decay: 0.01
  warmup_steps: 100
  eval_steps: 200
  save_steps: 200
  logging_steps: 50
  report_to: ["tensorboard", "wandb"]
  push_to_hub: true
  early_stopping_patience: 3

resume:
  model_id: null
  ckpt_step: null