config_name: "wikipedia-en-2K-s42_RTX3090_e10-lr1e-4"

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${config_name}

task: "wikipedia"
lang: "en"

seed: 42
device: "auto" # "auto" will use the best available device (CUDA > MPS > CPU)

model_id: "FacebookAI/xlm-roberta-base"
model_name: "XLM-R-Base"

lora:
  rank: 8
  alpha: 8
  dropout: 0.1
  target_modules: [
    # Not "all-linear" - exclude "qa_outputs" for QA
    "query",
    "key",
    "value",
    # Not all "dense" - exclude "lm_head.dense" for MLM
    "intermediate.dense",
    "output.dense",
  ]

data:
  train_size: 2000
  val_size: 500
  mlm_prob: 0.15

train:
  mini_batch_size: 8
  grad_accum_steps: 4
  num_epochs: 10
  max_steps: null
  lr: 1e-4
  lr_scheduler_type: "cosine"
  optim: "adamw_torch_fused"
  max_grad_norm: 1.0
  weight_decay: 0.01
  warmup_steps: 50
  eval_strategy: "steps"
  eval_steps: 100
  save_steps: 100
  load_best_model_at_end: true
  logging_steps: 50
  report_to: ["tensorboard", "wandb"]
  push_to_hub: true
  early_stopping_patience: 5

resume:
  model_id: null
  ckpt_step: null
